name: streamlit-conda-minimal
channels:
  - conda-forge
dependencies:
  - fenics
  - streamlit
  - chromadb
  - pypdf
  - tiktoken
  - pyautogen
  - pyautogen[gemini]
  - pyautogen[gemini,retrievechat,lmm]
  - pillow